version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/share_stewardship"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "ss-dag-development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "ss-dag-development"
