version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/share_stewardship"
    schedule:
      interval: "weekly"
    target-branch: "ss-dag-development"
    open-pull-requests-limit: 10

