
name: Rust CI

on:
  push:
    branches: [ ss-dag-development ]
  pull_request:
    branches: [ ss-dag-development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Check Formatting
      run: cargo fmt -- --check
      working-directory: share_stewardship

    - name: Run Linter (Clippy)
      run: cargo clippy -- -D warnings -A dead_code -A clippy::upper_case_acronyms
      working-directory: share_stewardship

    - name: Build
      run: cargo build --verbose
      working-directory: share_stewardship

    - name: Run Tests
      run: cargo test --verbose
      working-directory: share_stewardship