name: Rust CI

on:
  push:
    branches: [ ss-dag-development ]
  pull_request:
    branches: [ ss-dag-development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Check Formatting
      run: cargo fmt -- --check
      working-directory: share_stewardship

    - name: Run Linter (Clippy)
      run: cargo clippy -- -D warnings -A dead_code -A clippy::upper_case_acronyms
      working-directory: share_stewardship

    - name: Build
      run: cargo build --verbose
      working-directory: share_stewardship

    - name: Run Tests
      run: cargo test --all --verbose
      working-directory: share_stewardship

    - name: Generate Coverage Report
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.25.2'
        args: '--verbose --workspace'
        working-directory: share_stewardship

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: cobertura.xml

    - name: Verify Codecov upload
      run: echo "Coverage report uploaded to Codecov."
