name: Rust CI

on:
  push:
    branches: [ ss-dag-development ]
  pull_request:
    branches: [ ss-dag-development ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Ensure Rust code is formatted properly
      - name: Check Formatting
        run: cargo fmt -- --check
        working-directory: share_stewardship

      # Enforce code quality with Clippy
      - name: Run Linter (Clippy)
        run: cargo clippy -- -D warnings -A dead_code -A clippy::upper_case_acronyms
        working-directory: share_stewardship

      # Verify the code compiles successfully
      - name: Build
        run: cargo build --verbose
        working-directory: share_stewardship

      # Execute unit tests
      - name: Run Unit Tests
        run: cargo test --verbose
        working-directory: share_stewardship

      # Execute integration tests
      - name: Run Integration Tests
        run: cargo test --tests --verbose
        working-directory: share_stewardship

      # Install cargo-tarpaulin for coverage reports
      - name: Install cargo-tarpaulin
        uses: taiki-e/install-action@cargo-tarpaulin

      # Generate Code Coverage Report
      - name: Generate Coverage Report
        run: cargo tarpaulin --verbose --workspace --out Xml
        working-directory: share_stewardship

      # Upload generated coverage report to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cobertura.xml

      - name: Verify Codecov upload
        run: echo "Coverage report uploaded to Codecov."

      # Verify code compiles and tests pass in release mode
      - name: Run Tests with All Features (Release)
        run: cargo test --all-features --release
        working-directory: share_stewardship

      # Benchmark performance
      - name: Run Benchmarks
        run: cargo bench
        working-directory: share_stewardship

      # Run Security Audit to check dependencies
      - name: Security Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on audit failure
        if: failure()
        run: echo "Security vulnerabilities found! Please review immediately."
